element_desktop_autostart: true
signal_desktop_autostart: true
syncthing_autostart: true
host_roles:
# start
  - apt_update_upgrade
# random order
  - common_packages
  - element_desktop
  - firefox
  - fluffychat
  - git
  - keepassxc
  - signal_desktop
  - syncthing
  - vscodium
  - zsh
# end
  - autostart
  - keybindings