autostart_element: true
autostart_signal: true
host_roles:
# start
  - apt_update_upgrade
# random order
  - common_packages
  - element_desktop
  - firefox
  - git
  - keepassxc
  - signal_desktop
  - vscodium
  - zsh
# end
  - autostart
  - keybindings