autostart_element: true
autostart_signal: true
syncthing_autostart: true
host_roles:
# start
  - apt_update_upgrade
# random order
  - element_desktop
  - firefox
  - git
  - keepassxc
  - signal_desktop
  - syncthing
  - vscodium
  - zsh
# end
  - autostart
  - keybindings