host_roles:
# start
  - init
# random order
  - appsWithoutSetup
  - firefox
  - git
  - mpv
  - scripts
  - signal
  - syncthing
  - thumbnailer
  - vscodium
  - ytdlp
  - zsh
# end
  - autostart
  - keybindings