host_roles:
# start
  - apt_update_upgrade
  - init
# random order
  - appsWithoutSetup
  - dotnet
  - firefox
  - git
  - mpv
  - rust
  - scripts
  - signal
  - streamdeck
  - syncthing
  - thumbnailer
  - vscodium
  - ytdlp
  - zsh
# end
  - autostart
  - keybindings