- name: Install common apt packages
  ansible.builtin.apt:
    name:
      - ansible-lint
      - gnome-shell-extensions
      - helvum
      - libreoffice
      - pavucontrol
      - pdfarranger

- name: Install common snap packages
  community.general.snap:
    name:
      - spotify