- name: Install common apt packages
  ansible.builtin.apt:
    name:
      - ansible-lint
      - ffmpegthumbnailer
      - gnome-shell-extensions
      - helvum
      - libreoffice
      - mumble
      - pavucontrol
      - pdfarranger
      - pulseaudio-utils
      - simple-scan
      - streamlink

- name: Install common snap packages
  community.general.snap:
    name:
      - spotify