---

- name: Host a-laptop
  become: true
  connection: local
  hosts: a-laptop
  roles:
  # start
    - init
  # random order
    - appsWithoutSetup
    - firefox
    - git
    - mpv
    - scripts
    - syncthing
    - thumbnailer
    - vscodium
    - ytdlp
    - zsh
  # end
    - autostart
    - keybindings
  vars_files:
    - vars.yml

- name: Host a-pc
  become: true
  connection: local
  hosts: a-pc
  roles:
  # start
    - init
  # random order
    - appsWithoutSetup
    - dotnet
    - firefox
    - git
    - mpv
    - scripts
    - streamdeck
    - syncthing
    - thumbnailer
    - vscodium
    - ytdlp
    - zsh
  # end
    - autostart
    - keybindings
  vars_files:
    - vars.yml

- name: Host a-tv-box
  become: true
  hosts: a-tv-box
  remote_user: pi
  pre_tasks:
    - name: Update and upgrade apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
  roles:
  # start
    - guest_user
    - rpi_first_boot_wizard
  # random order
    - firefox