---

- name: All hosts
  hosts: all
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Run roles for this hostgroup
      ansible.builtin.include_role:
        name: "{{ role_name }}"
      loop: "{{ host_roles }}"
      loop_control:
        loop_var: role_name