---
- name: Install packages
  package:
    name:
      - ansible-lint
      - deja-dup
      - exfatprogs
      - libreoffice
      - mumble
      - pavucontrol
      - pdfarranger
      - python3-psutil
      - simple-scan
      - streamlink
      - vlc

- name: Install snap packages
  snap:
    name:
      - keepassxc
      - spotify

- name: Add to keybindings_dict
  set_fact:
    keybindings_dict: "{{ keybindings_dict | combine({'<Primary><Alt>k': 'keepassxc'}) }}"