- name: Install 'zsh'
  package:
    name: zsh

- name: Copy settings file
  copy:
    dest: "/home/{{ remote_user_name }}/.zshrc"
    group: "{{ remote_user_name }}"
    mode: "644"
    owner: "{{ remote_user_name }}"
    src: .zshrc

- name: Set zsh as default shell
  user:
    name: "{{ remote_user_name }}"
    shell: "/bin/zsh"