- name: Set keybinding for web browser
  become_user: "{{ remote_user_name }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/www"
    value: "['<Primary><Alt>b']"

- name: Set custom-keybindings binding
  become_user: "{{ remote_user_name }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom{{ loop_index }}/binding"
    value: "'{{ item.key }}'"
  loop: "{{ keybindings_dict | dict2items }}"
  loop_control:
    index_var: loop_index

- name: Set custom-keybindings command
  become_user: "{{ remote_user_name }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom{{ loop_index }}/command"
    value: "'{{ item.value }}'"
  loop: "{{ keybindings_dict | dict2items }}"
  loop_control:
    index_var: loop_index

- name: Set custom-keybindings name
  become_user: "{{ remote_user_name }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom{{ loop_index }}/name"
    value: "'{{ item.value }}'"
  loop: "{{ keybindings_dict | dict2items }}"
  loop_control:
    index_var: loop_index

- name: Build keybindings_list
  set_fact:
    keybindings_list: >
      {{
        keybindings_list | default([]) +
        [ single_quote ~ '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom' ~ loop_index ~ '/' ~ single_quote ]
      }}
  loop: "{{ keybindings_dict | dict2items }}"
  loop_control:
    index_var: loop_index

- name: Set custom-keybindings array
  become_user: "{{ remote_user_name }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "{{ '[' ~ keybindings_list | join(', ') ~ ']' | string }}"
  when: keybindings_list | length > 0