- name: Install 'yt-dlp'
  package:
    name: yt-dlp

- name: Create config dir
  file:
    group: "{{ remote_user_name }}"
    mode: '700'
    owner: "{{ remote_user_name }}"
    path: "/home/{{ remote_user_name }}/.config/yt-dlp"
    state: directory

- name: Copy settings file
  copy:
    dest: "/home/{{ remote_user_name }}/.config/yt-dlp/config"
    group: "{{ remote_user_name }}"
    mode: '644'
    owner: "{{ remote_user_name }}"
    src: config